# Generated by Django 6.0.5 on 2026-05-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['arrival_date', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity_type', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itinerary.stop')),
            ],
        ),
    ]
